# -*- coding: utf-8 -*-
"""pass_gen.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ILOehIFCwCcLmcTm9nbjPhFwtj3AVfAF
"""

import random
import string

def generate_random_password(length, include_special_chars):
    # Define the alphanumeric and special characters
    if include_special_chars:
        all_characters = string.ascii_letters + string.digits + string.punctuation
    else:
        all_characters = string.ascii_letters + string.digits

    # Generate a string of random alphanumeric (and special) characters
    random_password = ''.join(random.choices(all_characters, k=length))
    return random_password

def user_input():
    while True:
        try:
            length = int(input("How many characters do you want your password to be? "))
            if length <= 0:
                print("Please enter a number greater than 0.")
            else:
                break
        except ValueError:
            print("Please enter a valid integer.")

    while True:
        spec_char = input("Do you want your password to contain special characters? (Y/N): ").strip().lower()
        if spec_char in ('y', 'n'):
            include_special_chars = (spec_char == 'y')
            break
        else:
            print("Please enter 'Y' for yes or 'N' for no.")

    return length, include_special_chars

def main():
    length, include_special_chars = user_input()
    password = generate_random_password(length, include_special_chars)
    print("Generated password:", password)

if __name__ == "__main__":
    main()